# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5509a3dcd96b322fbfe2055193879a3d9ec78f3fb72a091b130c84b49ce64f560cd628fa3b97f0de2412d7559daf9d2e75f9fe6f74cff7092a31f750a708dc

test:
  secret_key_base: 5889451b1ad0cae741b2762c4e06fc490dcc554c9198f6178c263cba2d5e2349ff4bfc5ec91180434479682220c405bd768ede2459f8f2e6a8c0fd5343fb5327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
